name: CI/CD Pipeline

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'pre-prod'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # Instalar Docker Compose desde el binario
      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          DOCKER_COMPOSE_VERSION=2.20.0
          sudo curl -L "https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Start application
        run: |
          docker-compose up -d app
          docker ps
        
      - name: Check container logs
        run: |
          docker logs $(docker ps -q --filter "name=app")
        
      - name: Wait for the application to be ready
        run: |
          echo "Waiting for web service to be healthy..."
          for i in {1..5}; do
            if curl -sSf http://localhost:3000 > /dev/null; then
              echo "Web service is up!"
              exit 0
            fi
            echo "Waiting for web service to be up ($i/5)..."
            sleep 5
          done
          echo "Web service did not start in time"
          exit 1
        

      - name: Run Selenium tests
        run: npm run test:e2e

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: mochawesome-report

      - name: Set up SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
